name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore LilyAbramSite.Wasm/LilyAbramSite.Wasm.csproj
    - name: Build
      run: dotnet build LilyAbramSite.Wasm/LilyAbramSite.Wasm.csproj --configuration Release --no-restore
    - name: Publish
      run: dotnet publish LilyAbramSite.Wasm/LilyAbramSite.Wasm.csproj -c Release --no-build -o publishOutput
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: publishOutput/wwwroot
